version: "3.1"

services:
    db:
        container_name: dq-db
        restart: always
        build: 
            context: ./db
        ports:
            - 3306:3306
        
        environment:
            MYSQL_ROOT_PASSWORD: vqd2020
            MYSQL_DATABASE: dataquality
            MYSQL_USER: dq
            MYSQL_PASSWORD: vqd2020
    
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    
    app:
        container_name: dq-app
        restart: always
        links: 
            - db
        depends_on: 
            - db
        build: 
            context: ./app
        command: >
            bash -c "sleep 20 && python manage.py runserver 0.0.0.0:8000"
        ports:
            - 8000:8000